### PR TITLE
Add Reset Button

### LINKED ISSUE #20: Reset Highscore button
Hi, I'm thinking of having a "RESET" button which resets the highscore value to zero,

I need your feedback on this.

Either we can add it like this so that after hovering on "High Score", "RESET" button is displayed and can be clicked.
image

Or we can add it below the highscore
image

### PR DESCRIPTION
**Pull request by manaslohani**
Closes #20 
* Added a Reset Button to reset highscore.
* It also resets the scores from the local storage 
Screenshot from 2022-10-16 01-12-37

### CODE REVIEW

**Review by uday03meh — CHANGES_REQUESTED** [review]
It works perfectly, can you please change the design and hover state ?

I feel like it is grabbing user's attention from the game. Maybe remove the yellow border or try something yourself.

**Comment by manaslohani** [comment]
Okay , Does removing the yellow border and removing the hover state work for you?

**Comment by uday03meh** [comment]
Yes, and maybe change text color to grey-like color on hovering

**Comment by manaslohani** [comment]
Changed the style for the reset button

**Comment by uday03meh** [comment]
Perfect.
Thanks for contributing!

**Pull request merged**
