### PR TITLE
Rectified the Score-Rendering and Reference Error

### LINKED ISSUE #36: Production in halt; error in rendering scores
- While running the game, I faced two errors: Syntax Error and Reference Error.
- Origin:
  - scoreAfter is not rendered properly 
  - data stored in localStorage is reverted to JSON string "0,0" from "[0,0]"
  - Undefined whitespace in innerText caused Reference error

> I would like to work on this issue, so would you please assign me to this

## Errors Faced

| CONSOLE | LOCAL STORAGE| 
|-|-|
| |  |

### PR DESCRIPTION
**Pull request by Mano-08**
## Changes made:
```diff
+ Changed format of scores stored from JSON string "0,0" to JSON string(array) "[0,0]"
+ Uploaded scores into local storage only when necessary
+ Added comments near local storage variables for improving the readability of code
- Removed repeated localStorage.setItem() to update local storage only when changes occur with the player's moves
```

### CODE REVIEW

**Comment by uday03meh** [comment]
Thank you so much @Mano-08!

**Comment by uday03meh** [comment]
Website is working perfectly in [Deploy Preview](https://deploy-preview-37--uday03meh-rock-paper-scissors.netlify.app/) of this PR, but actual website is still showing these errors in the console

image

**Comment by Mano-08** [comment]
Oh, the website worked as expected on my local machine too. 
Anyways, I will look into the error.

**Comment by Mano-08** [comment]
I found the bug! 
It's not in the code but after the 'reset' button was added, inside the resetGame() function "0,0" was set into local storage instead of "[0,0]". So if at any point you reset the game and directly refresh the page, "0,0" remains in local storage forever. and JSON.parse() finds "," inside "0,0" as a "non-whitespace" character and throws error immediately.

I will update the code and look for any edge case.

**Comment by uday03meh** [comment]
Really complicated stuff for me to grasp 😅
It works perfectly now without any errors
Thanks again Mano🥹

**Comment by Mano-08** [comment]
Took me a while to understand it myself lol😅
You're welcome! glad that its running without errors🥳

**Pull request merged**
